name: CI workflow
on: workflow_dispatch
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: mvn clean  install
