name: CI workflow
on: 
  push:
    branches: main
  pull_request: 
    branches: main
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run:  mvn clean install -U
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          VERIFY_EMAIL_HOST: ${{ secrets.VERIFY_EMAIL_HOST }}
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/furniture-api-repo:latest .
      - name: Login in Docker Hub
        env:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p $password
      - run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/furniture-api-repo:latest
         
