name: CI workflow
on: 
  push:
    branches: main
  pull_request: 
    branches: main
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run:  mvn clean install -U
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          VERIFY_EMAIL_HOST: ${{ secrets.VERIFY_EMAIL_HOST }}
         
